# #1 year=365 days
# 1 year=12 weeks
# 1 year=12 months
current_age = input("Enter your current age")
c = float(current_age)
days = (90 - c) * 365
weeks = (90 - c) * 52
months = (90 - c) * 12
print(f"The days you will live = {days}")
print(f"the weeks you will leave={weeks}")
print(f"the months you would leave = {months}")
